FORMAT: 1A
HOST: http://example.com/api/1

# Portfolio

An API to supply content for a portfolio site, including articles, projects, clients.

## Project [/project]

### Get Project stubs and titles [GET]

+ Response 200 (application/json)

    + Body

            {
                "result": [{
                    "id": "example_project_1",
                    "title": "Example Project 1"},
                    {
                    "id": "example_project_1",
                    "title": "Example Project 1"},
                    {
                    "id": "example_project_1",
                    "title": "Example Project 1"}]
            }