FORMAT: 1A
HOST: http://example.com/api/1

# Portfolio

An API to supply content for a portfolio site, including articles, projects, clients.

## Project [/project]

### Get Project stubs and titles [GET]

+ Response 200 (application/json)

    + Body

            {
                "result": [{
                    "id": "example_project_1",
                    "title": "Example Project 1"},
                    {
                    "id": "example_project_2",
                    "title": "Example Project 2"},
                    {
                    "id": "example_project_3",
                    "title": "Example Project 3"}]
            }


## Project [/project/{projectId}]

A project has the following attributes:

+ title
+ date
+ clients
+ role
+ technologies
+ description
+ images
+ urls

+ Parameters
    + projectId: example (required, string) - ID of the project

### View a project detail [GET]

+ Response 200 (application/json)

    + Body

            {
                "result": {
                    "id": "example_project_1",
                    "title": "Example Project 1",
                    "date": "November 2016",
                    "clients": [
                    ],
                    "role": "Developer",
                    "technologies": [
                        "React",
                        "Redux",
                        "API Blueprint",
                        "Express",
                        "Universal JavaScript",
                        "Babel"
                    ],
                    "description": "Development of an example site.",
                    "images": [
                        "desktop.png",
                        "mobile.png"
                    ],
                    "urls": [
                        "http://www.example.com"
                    ]
                }
            }
